(async function(){
  const $=id=>document.getElementById(id),config=window.ROVOCAR_SUPABASE||{},configured=/^https:\/\/.+\.supabase\.co$/.test(config.url)&&Boolean(config.publishableKey),client=configured&&window.supabase?window.supabase.createClient(config.url,config.publishableKey):null;
  const els={auth:$('adminAuthBtn'),status:$('adminStatus'),content:$('adminContent'),error:$('adminError'),errorText:$('adminErrorText'),cards:$('summaryCards'),table:$('userTable'),search:$('adminSearch'),deckPanel:$('deckPanel'),deckTitle:$('selectedUserTitle'),deckList:$('adminDeckList')};let users=[];
  const esc=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const date=value=>value?new Intl.DateTimeFormat('ko-KR',{dateStyle:'medium',timeStyle:'short'}).format(new Date(value)):'-';
  function fail(message){els.status.textContent='권한을 확인하지 못했습니다.';els.content.classList.add('hidden');els.error.classList.remove('hidden');els.errorText.textContent=message;}
  function render(){const q=els.search.value.trim().toLowerCase(),shown=users.filter(user=>!q||user.display_name.toLowerCase().includes(q));els.table.innerHTML=shown.map(user=>`<div class="user-row"><div><b>${esc(user.display_name)}</b><small>${esc(user.user_id.slice(0,8))}…</small></div><div class="metric">${user.visit_count}<span>접속</span></div><div class="metric">${user.deck_count}<span>단어장</span></div><div class="metric">${user.unique_word_count}<span>고유 단어</span></div><div class="metric">${user.total_attempts}<span>풀이</span></div><button class="view-decks" data-user="${esc(user.user_id)}" data-name="${esc(user.display_name)}">단어장 보기</button></div>`).join('')||'<p>표시할 사용자가 없습니다.</p>';}
  async function load(){const {data,error}=await client.rpc('admin_user_overview');if(error)throw error;users=data||[];els.cards.innerHTML=`<div><b>${users.length}</b><span>로그인 사용자</span></div><div><b>${users.reduce((n,u)=>n+Number(u.visit_count),0)}</b><span>누적 접속</span></div><div><b>${users.reduce((n,u)=>n+Number(u.deck_count),0)}</b><span>전체 단어장</span></div><div><b>${users.reduce((n,u)=>n+Number(u.unique_word_count),0)}</b><span>등록된 고유 단어</span></div>`;render();els.content.classList.remove('hidden');els.error.classList.add('hidden');els.status.textContent=`최근 갱신 ${date(new Date())}`;}
  async function showDecks(id,name){const {data,error}=await client.rpc('admin_deck_overview',{target_user_id:id});if(error)throw error;els.deckTitle.textContent=`${name}님의 단어장`;els.deckList.innerHTML=(data||[]).map(deck=>`<div class="deck-row"><b>${esc(deck.name)}</b><div class="metric">${deck.word_count}<span>단어</span></div><div class="metric">${deck.total_attempts}<span>풀이</span></div><div>${date(deck.updated_at)}</div></div>`).join('')||'<p>단어장이 없습니다.</p>';els.deckPanel.classList.remove('hidden');els.deckPanel.scrollIntoView({behavior:'smooth'});}
  els.auth.addEventListener('click',async()=>{if(!client)return fail('supabase-config.js에 프로젝트 연결값을 입력해 주세요.');const {data}=await client.auth.getSession();if(data.session)await client.auth.signOut();else await client.auth.signInWithOAuth({provider:'kakao',options:{redirectTo:`${location.origin}${location.pathname}`}});location.reload();});
  els.search.addEventListener('input',render);els.table.addEventListener('click',event=>{const button=event.target.closest('[data-user]');if(button)showDecks(button.dataset.user,button.dataset.name).catch(error=>fail(error.message));});$('closeDeckPanel').addEventListener('click',()=>els.deckPanel.classList.add('hidden'));
  if(!client)return fail('Supabase 프로젝트 연결 설정이 아직 필요합니다.');const {data}=await client.auth.getSession();if(!data.session){els.status.textContent='관리자 계정으로 로그인해 주세요.';return;}els.auth.textContent='로그아웃';try{await load();}catch(error){fail(error.message.includes('관리자')?'이 계정은 관리자 목록에 등록되지 않았습니다.':error.message);}
})();
