const STORAGE_KEY = 'rovocar:data:v1';
const REGISTRY_KEY = 'rovocar:registry:v1';
const state = { decks: [], registry: {}, currentDeckId: null, view: 'garage', game: null, deferredInstall: null, importWords: [], importTargetDeckId: null, storageKey: STORAGE_KEY, registryKey: REGISTRY_KEY, cloudUser: null, deckQuery: '' };
const $ = (id) => document.getElementById(id);
const els = Object.fromEntries(['garageView','deckView','gameView','resultView','deckGrid','deckTitle','deckSummary','masteryValue','wordCount','wordList','deckDialog','deckForm','deckNameInput','wordDialog','wordForm','wordDialogTitle','englishInput','koreanInput','editingWordId','gameModeLabel','gameTitle','gameCounter','routeFill','routeCar','promptLabel','promptText','wordRegistryLabel','speakBtn','answerForm','answerLabel','answerInput','feedback','nextBtn','resultScore','resultRate','resultMessage','retryWrongBtn','toast','installBtn','installDialog','csvInput','appendCsvInput','importDialog','importForm','importSummary','importDeckName','importPreview','importDialogTitle','importConfirmBtn','authBtn','syncBadge','deckSearch','deckResultCount','renameDeckBtn','deleteDeckBtn','renameDialog','renameForm','renameDeckInput'].map(id=>[id,$(id)]));

const uid = () => `${Date.now().toString(36)}${Math.random().toString(36).slice(2,7)}`;
const escapeHtml = (value) => String(value).replace(/[&<>'"]/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const normalizeEnglish = value => String(value).trim().toLowerCase().replace(/\s+/g,' ');
const normalizeKorean = value => String(value).trim().replace(/\s+/g,'').replace(/[.,·ㆍ]/g,'');
const shuffle = source => { const a=[...source]; for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]];} return a; };

function parseCsv(text){
  const rows=[]; let row=[], field='', quoted=false;
  for(let i=0;i<text.length;i++){const c=text[i], next=text[i+1]; if(c==='"'&&quoted&&next==='"'){field+='"';i++;}else if(c==='"'){quoted=!quoted;}else if(c===','&&!quoted){row.push(field);field='';}else if((c==='\n'||c==='\r')&&!quoted){if(c==='\r'&&next==='\n')i++;row.push(field);if(row.some(Boolean))rows.push(row);row=[];field='';}else field+=c;}
  if(field||row.length){row.push(field);rows.push(row);} return rows.slice(1).filter(r=>r[0]&&r.slice(1).some(Boolean)).map(r=>({id:uid(),english:r[0].trim(),korean:r.slice(1).join(',').trim(),attempts:0,correct:0}));
}
async function loadData(){
  if(loadFromStorage(state.storageKey))return;
  state.decks=[];state.registry={};save(false);
}
function loadFromStorage(key){try{const saved=localStorage.getItem(key);if(saved){state.decks=JSON.parse(saved);loadRegistry();return true;}}catch{}return false;}
function loadRegistry(){try{state.registry=JSON.parse(localStorage.getItem(state.registryKey)||'{}');}catch{state.registry={};}ensureRegistryNumbers();}
function registryNumber(english){const key=normalizeEnglish(english);if(state.registry[key])return state.registry[key];const next=Math.max(0,...Object.values(state.registry).map(Number))+1;state.registry[key]=next;return next;}
function ensureRegistryNumbers(){
  const repaired={},used=new Set();let next=1;
  for(const [key,value] of Object.entries(state.registry||{}).sort((a,b)=>Number(a[1])-Number(b[1]))){let no=Number(value);if(!Number.isInteger(no)||no<1||used.has(no)){while(used.has(next))next++;no=next;}repaired[key]=no;used.add(no);next=Math.max(next,no+1);}
  state.registry=repaired;
  for(const deck of [...state.decks].sort((a,b)=>new Date(a.createdAt)-new Date(b.createdAt)))for(const word of deck.words)word.registryNo=registryNumber(word.english);
}
let cloudSyncTimer;
function save(sync=true){ensureRegistryNumbers();localStorage.setItem(state.storageKey,JSON.stringify(state.decks));localStorage.setItem(state.registryKey,JSON.stringify(state.registry));if(sync&&state.cloudUser&&window.RoVoCloud){RoVoCloud.markDirty();clearTimeout(cloudSyncTimer);cloudSyncTimer=setTimeout(()=>RoVoCloud.sync(state.decks,state.registry).catch(()=>{}),700);}}
function currentDeck(){return state.decks.find(d=>d.id===state.currentDeckId);}
function deckStats(deck){const attempts=deck.words.reduce((n,w)=>n+(w.attempts||0),0),correct=deck.words.reduce((n,w)=>n+(w.correct||0),0);return {attempts,correct,rate:attempts?Math.round(correct/attempts*100):0};}
function showView(name){state.view=name;['garage','deck','game','result'].forEach(v=>els[`${v}View`].classList.toggle('hidden',v!==name));scrollTo({top:0,behavior:'smooth'});if(name==='garage')renderGarage();if(name==='deck')renderDeck();}
function renderGarage(){
  const query=state.deckQuery.trim().toLowerCase();const decks=[...state.decks].sort((a,b)=>new Date(b.createdAt)-new Date(a.createdAt)).filter(deck=>!query||deck.name.toLowerCase().includes(query));
  els.deckResultCount.textContent=query?`${decks.length}개 찾음`:`총 ${state.decks.length}개`;
  if(!decks.length){els.deckGrid.innerHTML=`<div class="empty-garage"><img src="assets/rovocar.svg" alt=""><h3>${state.decks.length?'검색 결과가 없어요':'차고가 비어 있어요'}</h3><p>${state.decks.length?'다른 이름으로 검색해 보세요.':'CSV를 불러오거나 직접 첫 단어장을 만들어 보세요.'}</p>${state.decks.length?'':'<button class="secondary-btn" type="button" data-new-empty>직접 만들기</button>'}</div>`;return;}
  els.deckGrid.innerHTML=decks.map((d,i)=>{const s=deckStats(d);return `<button class="deck-tile" data-deck="${d.id}" type="button"><span class="eyebrow">CAR ${String(i+1).padStart(2,'0')}</span><h3>${escapeHtml(d.name)}</h3><p class="tile-meta">${d.words.length}개 단어</p><span class="tile-bottom"><span class="tile-progress"><b>${s.rate}%</b><span>${s.attempts ? `${s.attempts}번 주행 기록` : '첫 주행 전'}</span></span><span class="tile-arrow">→</span></span></button>`}).join('');
}
function renderDeck(){
  const d=currentDeck();if(!d)return showView('garage');const s=deckStats(d);els.deckTitle.textContent=d.name;els.deckSummary.textContent=`${d.words.length}개의 단어가 이 차에 실려 있어요.`;els.masteryValue.textContent=`${s.rate}%`;els.wordCount.textContent=d.words.length;
  els.wordList.innerHTML=d.words.length?d.words.map(w=>`<div class="word-row"><span class="number" title="내 ${w.registryNo}번째 영어 단어">#${String(w.registryNo).padStart(4,'0')}</span><b>${escapeHtml(w.english)}</b><span>${escapeHtml(w.korean)}</span><button type="button" data-edit-word="${w.id}">수정</button></div>`).join(''):`<div class="empty-garage"><p>아직 실린 단어가 없어요. 단어를 먼저 추가해 주세요.</p></div>`;
}
function openDeckDialog(){els.deckForm.reset();els.deckDialog.showModal();setTimeout(()=>els.deckNameInput.focus(),30);}
function renameCurrentDeck(){const deck=currentDeck();if(!deck)return;els.renameDeckInput.value=deck.name;els.renameDialog.showModal();setTimeout(()=>els.renameDeckInput.select(),30);}
function deleteCurrentDeck(){const deck=currentDeck();if(!deck)return;if(!confirm(`“${deck.name}” 단어장과 학습 기록을 삭제할까요?\n이 작업은 되돌릴 수 없어요.`))return;state.decks=state.decks.filter(item=>item.id!==deck.id);state.currentDeckId=null;save();showView('garage');toast('단어장을 삭제했어요.');}
async function readCsvFile(file,targetDeckId=null){
  if(!file)return;try{const text=await file.text();const words=parseCsv(text);if(!words.length)throw new Error('English,Korean 열이 있는 CSV인지 확인해 주세요.');state.importWords=words;state.importTargetDeckId=targetDeckId;const target=state.decks.find(deck=>deck.id===targetDeckId);els.importDeckName.value=target?.name||file.name.replace(/\.csv$/i,'');els.importDeckName.closest('label').classList.toggle('hidden',Boolean(target));els.importDialogTitle.textContent=target?'CSV 단어 추가 확인':'CSV 단어장 확인';els.importConfirmBtn.textContent=target?'중복 제외하고 단어 추가':'이 단어장 만들기';els.importSummary.textContent=`${words.length}개의 단어를 찾았어요. 아래 미리보기를 확인해 주세요.`;els.importPreview.innerHTML=words.slice(0,12).map(w=>`<div><b>${escapeHtml(w.english)}</b><span>${escapeHtml(w.korean)}</span></div>`).join('')+(words.length>12?`<div><b>외 ${words.length-12}개</b><span>단어가 더 있어요.</span></div>`:'');els.importDialog.showModal();}catch(error){toast(error.message);}finally{els.csvInput.value='';els.appendCsvInput.value='';}}
function openWordDialog(word=null){els.wordForm.reset();els.editingWordId.value=word?.id||'';els.englishInput.value=word?.english||'';els.koreanInput.value=word?.korean||'';els.wordDialogTitle.textContent=word?'단어 고치기':'단어 싣기';els.wordForm.querySelector('.primary-btn').textContent=word?'수정 완료':'저장하고 다음 단어';$('finishAddingBtn').classList.toggle('hidden',Boolean(word));els.wordDialog.showModal();setTimeout(()=>els.englishInput.focus(),30);}
function storeWord(close=false){
  if(!els.wordForm.reportValidity())return false;const d=currentDeck(),editing=d.words.find(w=>w.id===els.editingWordId.value);if(editing){editing.english=els.englishInput.value.trim();editing.korean=els.koreanInput.value.trim();}else d.words.push({id:uid(),english:els.englishInput.value.trim(),korean:els.koreanInput.value.trim(),attempts:0,correct:0});save();renderDeck();if(close||editing){els.wordDialog.close();toast(editing?'단어를 수정했어요.':'단어를 실었어요.');}else{els.wordForm.reset();els.englishInput.focus();toast('단어를 싣고 다음 칸을 열었어요.');}return true;
}
function startGame(mode, words=null){const d=currentDeck();const source=words||d.words;if(!source.length){toast('게임을 시작하려면 단어를 먼저 추가해 주세요.');return;}state.game={mode,queue:shuffle(source),index:0,correct:0,wrong:[],answered:false};showView('game');els.gameModeLabel.textContent=mode==='en-ko'?'DRIVE 01':'DRIVE 02';els.gameTitle.textContent=d.name;renderQuestion();}
function renderQuestion(){const g=state.game,w=g.queue[g.index],total=g.queue.length,pct=total>1?g.index/(total-1)*100:0;g.answered=false;els.gameCounter.textContent=`${g.index+1} / ${total}`;const normalized=normalizeEnglish(w.english),matches=[...state.decks].sort((a,b)=>new Date(a.createdAt)-new Date(b.createdAt)).flatMap(deck=>deck.words).filter(word=>normalizeEnglish(word.english)===normalized),duplicateOrder=matches.findIndex(word=>word.id===w.id)+1,duplicateLabel=matches.length>1&&duplicateOrder>1?` · 중복 ${duplicateOrder}번째`:'';els.wordRegistryLabel.textContent=`MY WORD #${String(w.registryNo||registryNumber(w.english)).padStart(4,'0')}${duplicateLabel}`;els.routeFill.style.width=`${pct}%`;els.routeCar.style.left=`${pct}%`;els.promptLabel.textContent=g.mode==='en-ko'?'영어를 보고 한글 뜻을 입력하세요':'한글 뜻을 보고 영어 스펠링을 입력하세요';els.promptText.textContent=g.mode==='en-ko'?w.english:w.korean;els.answerLabel.textContent=g.mode==='en-ko'?'한글 뜻':'영어 스펠링';els.answerInput.placeholder=g.mode==='en-ko'?'뜻을 입력하세요':'스펠링을 입력하세요';els.answerInput.value='';els.answerInput.disabled=false;els.answerForm.querySelector('button').disabled=false;els.feedback.className='feedback hidden';els.nextBtn.classList.add('hidden');els.speakBtn.classList.toggle('hidden',g.mode!=='en-ko');setTimeout(()=>els.answerInput.focus(),40);}
function checkAnswer(){const g=state.game;if(g.answered)return;const value=els.answerInput.value;if(!value.trim()){toast('답을 먼저 입력해 주세요.');return;}const w=g.queue[g.index],expected=g.mode==='en-ko'?w.korean:w.english;const answers=expected.split(/[,/]| 또는 |;/).map(v=>g.mode==='en-ko'?normalizeKorean(v):normalizeEnglish(v));const mine=g.mode==='en-ko'?normalizeKorean(value):normalizeEnglish(value);const correct=answers.includes(mine);g.answered=true;w.attempts=(w.attempts||0)+1;if(correct){w.correct=(w.correct||0)+1;g.correct++;}else g.wrong.push(w);save();els.feedback.className=`feedback ${correct?'correct':'wrong'}`;els.feedback.innerHTML=correct?`<b>정답!</b> 그대로 다음 코스로 달려요.`:`<b>아쉬워요.</b> 정답은 <strong>${escapeHtml(expected)}</strong>예요.`;els.answerInput.disabled=true;els.answerForm.querySelector('button').disabled=true;els.nextBtn.textContent=g.index===g.queue.length-1?'결과 보기 →':'다음 단어 →';els.nextBtn.classList.remove('hidden');els.nextBtn.focus();}
function nextQuestion(){const g=state.game;if(g.index<g.queue.length-1){g.index++;renderQuestion();}else finishGame();}
function finishGame(){const g=state.game,total=g.queue.length,rate=Math.round(g.correct/total*100);els.resultScore.textContent=`${g.correct} / ${total}`;els.resultRate.textContent=`${rate}%`;els.resultMessage.textContent=rate===100?'모든 단어를 정확히 배송했어요!':rate>=70?'거의 다 왔어요. 틀린 단어만 한 번 더 달려 볼까요?':'천천히 다시 달리면 길이 익숙해질 거예요.';els.retryWrongBtn.classList.toggle('hidden',!g.wrong.length);showView('result');}
function speak(){const w=state.game?.queue[state.game.index];if(!w||!('speechSynthesis'in window))return;speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(w.english);u.lang='en-US';u.rate=.85;speechSynthesis.speak(u);}
let toastTimer;function toast(message){clearTimeout(toastTimer);els.toast.textContent=message;els.toast.classList.remove('hidden');toastTimer=setTimeout(()=>els.toast.classList.add('hidden'),2200);}

$('newDeckBtn').addEventListener('click',openDeckDialog);$('addWordBtn').addEventListener('click',()=>openWordDialog());
els.renameDeckBtn.addEventListener('click',renameCurrentDeck);els.deleteDeckBtn.addEventListener('click',deleteCurrentDeck);
els.renameForm.addEventListener('submit',e=>{e.preventDefault();if(!els.renameForm.reportValidity())return;const deck=currentDeck();if(!deck)return;deck.name=els.renameDeckInput.value.trim();save();els.renameDialog.close();renderDeck();toast('단어장 이름을 바꿨어요.');});
els.deckSearch.addEventListener('input',()=>{state.deckQuery=els.deckSearch.value;renderGarage();});
els.csvInput.addEventListener('change',()=>readCsvFile(els.csvInput.files[0]));els.appendCsvInput.addEventListener('change',()=>readCsvFile(els.appendCsvInput.files[0],state.currentDeckId));
els.importForm.addEventListener('submit',e=>{e.preventDefault();if(!state.importWords.length)return;if(state.importTargetDeckId){const deck=state.decks.find(item=>item.id===state.importTargetDeckId);if(!deck)return;const existing=new Set(deck.words.map(word=>normalizeEnglish(word.english)));const additions=state.importWords.filter(word=>!existing.has(normalizeEnglish(word.english)));deck.words.push(...additions);state.importWords=[];state.importTargetDeckId=null;save();els.importDialog.close();renderDeck();toast(`${additions.length}개 단어를 추가했어요.`);return;}if(!els.importForm.reportValidity())return;const d={id:uid(),name:els.importDeckName.value.trim(),createdAt:new Date().toISOString(),words:state.importWords};state.decks.unshift(d);state.currentDeckId=d.id;state.importWords=[];save();els.importDialog.close();showView('deck');toast('CSV 단어장을 차고에 넣었어요.');});
els.deckForm.addEventListener('submit',e=>{e.preventDefault();if(!els.deckForm.reportValidity())return;const d={id:uid(),name:els.deckNameInput.value.trim(),createdAt:new Date().toISOString(),words:[]};state.decks.unshift(d);state.currentDeckId=d.id;save();els.deckDialog.close();showView('deck');openWordDialog();});
els.wordForm.addEventListener('submit',e=>{e.preventDefault();storeWord(false);});$('finishAddingBtn').addEventListener('click',()=>storeWord(true));
els.deckGrid.addEventListener('click',e=>{const b=e.target.closest('[data-deck]');if(b){state.currentDeckId=b.dataset.deck;showView('deck');}});
els.wordList.addEventListener('click',e=>{const b=e.target.closest('[data-edit-word]');if(b)openWordDialog(currentDeck().words.find(w=>w.id===b.dataset.editWord));});
document.addEventListener('click',e=>{const close=e.target.closest('[data-close-dialog]');if(close)close.closest('dialog')?.close();const go=e.target.closest('[data-go]');if(go)showView(go.dataset.go);const mode=e.target.closest('[data-mode]');if(mode)startGame(mode.dataset.mode);if(e.target.closest('[data-new-empty]'))openDeckDialog();});
els.answerForm.addEventListener('submit',e=>{e.preventDefault();checkAnswer();});els.nextBtn.addEventListener('click',nextQuestion);els.speakBtn.addEventListener('click',speak);$('quitGameBtn').addEventListener('click',()=>showView('deck'));els.retryWrongBtn.addEventListener('click',()=>startGame(state.game.mode,state.game.wrong));
const isIosDevice=/iphone|ipad|ipod/i.test(navigator.userAgent)||(navigator.platform==='MacIntel'&&navigator.maxTouchPoints>1);
const isStandalone=window.matchMedia('(display-mode: standalone)').matches||navigator.standalone===true;
if(isIosDevice&&!isStandalone){document.body.classList.add('ios-browser');els.installBtn.classList.remove('hidden');}
window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();state.deferredInstall=e;els.installBtn.classList.remove('hidden');});
els.installBtn.addEventListener('click',async()=>{if(state.deferredInstall){state.deferredInstall.prompt();await state.deferredInstall.userChoice;state.deferredInstall=null;els.installBtn.classList.add('hidden');return;}if(isIosDevice&&!isStandalone){els.installDialog.showModal();return;}toast('브라우저 메뉴에서 앱 설치 또는 홈 화면에 추가를 선택해 주세요.');});
window.addEventListener('appinstalled',()=>{state.deferredInstall=null;els.installBtn.classList.add('hidden');});
if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('sw.js'));
function renderAccount(){const user=state.cloudUser;els.authBtn.innerHTML=user?`<span>●</span> ${escapeHtml(user.name)} · 로그아웃`:'<span>●</span> 카카오 로그인';els.syncBadge.textContent=user?'동기화됨':'기기 저장';els.syncBadge.className=`sync-badge ${user?'synced':''}`;}
async function handleAuth(user){const previous=state.cloudUser;state.cloudUser=user;if(user){const userKey=`${STORAGE_KEY}:${user.id}`,registryKey=`${REGISTRY_KEY}:${user.id}`;const guestDecks=state.decks,guestRegistry=state.registry;state.storageKey=userKey;state.registryKey=registryKey;if(!loadFromStorage(userKey)){state.decks=guestDecks;state.registry=guestRegistry;ensureRegistryNumbers();}try{const remote=await RoVoCloud.sync(state.decks,state.registry);if(remote){state.decks=remote.decks;state.registry=remote.registry;ensureRegistryNumbers();}save(false);}catch(error){toast(`동기화하지 못했어요: ${error.message}`);}}else if(previous){state.storageKey=STORAGE_KEY;state.registryKey=REGISTRY_KEY;state.decks=[];state.registry={};await loadData();}state.currentDeckId=null;renderAccount();showView('garage');}
window.addEventListener('rovocar-cloud',event=>{const detail=event.detail;if(detail.type==='auth')handleAuth(detail.user);if(detail.type==='syncing'){els.syncBadge.textContent='동기화 중';els.syncBadge.className='sync-badge syncing';}if(detail.type==='synced'){els.syncBadge.textContent='동기화됨';els.syncBadge.className='sync-badge synced';}if(detail.type==='offline'){els.syncBadge.textContent='오프라인 저장';els.syncBadge.className='sync-badge';}if(detail.type==='error'){els.syncBadge.textContent='동기화 대기';els.syncBadge.className='sync-badge error';}if(detail.type==='online'&&state.cloudUser)RoVoCloud.sync(state.decks,state.registry).then(remote=>{if(remote){state.decks=remote.decks;state.registry=remote.registry;save(false);renderGarage();}}).catch(()=>{});});
els.authBtn.addEventListener('click',async()=>{try{if(state.cloudUser){clearTimeout(cloudSyncTimer);els.authBtn.disabled=true;await RoVoCloud.flush(state.decks,state.registry);await RoVoCloud.signOut();els.authBtn.disabled=false;}else await RoVoCloud.signIn();}catch(error){els.authBtn.disabled=false;toast(error.message);}});
loadData().then(async()=>{renderGarage();renderAccount();if(window.RoVoCloud)await RoVoCloud.init();});
